### ISSUE TITLE
Set attribution options

### ISSUE THREAD

**Issue by BjornW** [tarmot/wp-cc-plugin#10]
I'm suggesting the following for dealing with attribution: 

A dropdown with depending on the location of the attribution dropdown the following options: 
- Network Name  (only on Network level of settings)
- Network URL  ((only on Network level of settings)
- Site Name  ( on Network && Site level of settings)
- Site URL  ( on Network && Site level of settings)
- Author Nickname  ( on Network && Site && User level of settings)
- Author Display Name  ( on Network && Site && User level of settings)
- Other  ( on Network && Site && User level of settings)

When other is chosen as an option I'll add an input field using some Javascript magic so the user can input some freeform text.

@tarmot: What do you think about this?

**Comment by tarmot** [comment]
Not sure I understand. In terms of the license metadata, a URL is a separate field, and to my mind should be populated by the exact URL (permalink) of the resource for which a CC license is being shown.

The license chooser has these metadata fields, which we'd need to populate:
- Title of work: fill with resource title automatically
- Attribute work to name: author's name; I'd just use the same name that the author has chosen to be their visible name in the blog, but it could be a separate choice as well if you think it's needed (freeform text field in user properties)
- Attribute work to URL: the permalink of the resource, automatically filled
- Source work URL: this would be a resource-specific optional field, in case the resource is an adaptation of something else
- More permissions URL: this would be either a blog or author level setting

Let's keep it simple and as automatic as possible, with good default values.

**Comment by BjornW** [comment]
Just to clarify: I was more thinking along the lines of whom should be credited. For example a Network could decide to make the Network as a whole take credit, instead of the author of the page/post. So therefor I was mentioning those options. Hopefully I will have something to show soonish so you can see what I meant :)

**Comment by tarmot** [comment]
OK, the license propagation works correctly now. But how to handle showing of a) title and b) author?

If license customization is enabled, then things are trivial: Show the most closely matching title and author (eg. individual post title and author).

But if license overrides aren't allowed, then there's probably some separate alternatives:
1. All content is labeled according to blog admin decision: blog title and blog author.
2. Admin allows more finegrained attribution, so each post shows the post title and post author.

Would it be enough to have this as an additional option in the blog level? Option "Give attribution to individual post authors?"

**Comment by tarmot** [comment]
While adding author name display to the widget, I figured out that having a choice of "author display name" at aggregate views does not make any sense. There's no such thing as a single author for a blog, let alone a network. So for network or site level licenses, only options "site name" or "something else" make sense, whereas for single post views, also the "author name" is possible.

**Comment by tarmot** [comment]
I’m proposing something like this:

NETWORK ADMIN
1. License selection
   a [ ] Use single license for entire network. (disables 3)
   b [ ] Allow different licenses for each blog. (disables 3b)
   c [ ] Allow post-specific licenses.
2. Attribution
   a [ ] Attribute all to network: (title), (author) (disables 4)
   b [ ] Allow different attribution for each blog. (disables 4b)
   c [ ] Allow post-specific attribution.

BLOG ADMIN
1. License selection
   a [ ] Use single license for entire blog.
   b [ ] Allow post-specific licenses.
2. Attribution
   a [ ] Attribute all to blog: (title), (author)
   b [ ] Attribute to author

And I would not separate allowing author-specific license and post-specific license. If authors can choose their licenses, then it makes sense to have a default on their profile and then the possibility to customize it.

**Comment by BjornW** [comment]
I don't necessarily agree with "There's no such thing as a single author for a blog". Actually I would say that most, if not all WordPress installs (in which WordPress is used as a blog) would have only one author. Due to the fact that WordPress is being used more and more as a platform/framework instead of just a blog, this might longer matter that much.  

The issue you describe: "having a choice of "author display name" at aggregate views does not make any sense" is only true if we can _only_ display one license. However, it is possible to display multiple licenses in the same page (See also my mail with CC-devel and the answer from Peter http://lists.ibiblio.org/pipermail/cc-devel/2013-November/001958.html). This is exactly the problem we've discussed on Skype and I'm pretty sure we can solve this (for this first version at least) by: 

1) Add a warning text to the license in widget
2) Add a filter which automatically adds the license to a post/page content so it becomes instantly clear what the license is for this particular post/page (which does not yet solve the issue of possible having a different license for attached media such as images, video etc).        

The warning text has been added (although it needs to be an option for admins) and the filter can be added soonish. In my opinion this would entail the first 'alpha' version of the new plugin which we can use to gather more feedback. 

Therefor I'd to propose to finish the above mentioned changes before further researching / implementing the workflow you suggested, as this is not a small change, if I understand it correctly. 

This does not mean that I think that the current implemented flow of selecting a license is finished or the best way of dealing with selecting a license and adding metadata. This is merely my attempt to stay on schedule :) so we have a first version ready as soon as possible which we can use to test our assumptions.   

Btw I've added some descriptions on how your suggested flow would function in my own words, to see if I understood you correctly, please let my know if I'm on the right path.

NETWORK ADMIN
1. License selection (I presume only one option may be chosen, radiobuttons)
   a [ ] Use single license for entire network, site admins cannot choose their own license for a blog nor can authors for their posts. The license settings in the blog admin are hidden, only the selected license is visible as read-only. 

b [ ] Allow different licenses for each blog, site admins may change the site/blog license _ONLY_ per site/blog. They cannot select a license per post unless the option 'Allow post-specific licenses' is selected in the Network Admin. The option 'Allow post-specific licenses' is hidden in the blog admin.   Authors cannot select a license.

c [ ] Allow post-specific licenses. If this option is selected it allows a site admin to enable post-specific licenses on her specific blog(s)/site(s) AND to choose a license for their specific blog/site. It does nothing else. If this option is _NOT_ selected the option 'Allow post-specific licenses' in the blog admin is not shown.
1. Attribution (I presume only one option may be chosen, so radiobuttons)
   a [ ] Attribute all to network: (title), (author). Attribution settings are hidden in the blog admin. Is this a dropdown with the option of the Network Title and the author of a post? Or is this just the author picked by the superadmin? What about the url for the attribution?

b [ ] Allow different attribution for each blog. Attribution settings are shown in the blog admin, but the the site admin may only set attribution for all content of the specific blog. Attribution cannot be set per post. 

c [ ] Allow post-specific attribution. Authors may choose their own attribution if they want.

BLOG ADMIN
1. License selection
   a [ ] Use single license for entire blog, authors are not able to select their own license.
   b [ ] Allow post-specific licenses, authors are allowed to pick their own license per post or the post will be licensed according to the user's default license.
2. Attribution
   a [ ] Attribute all to blog: (title), (author)
   b [ ] Attribute to author

What's the difference between 4.a author and 4.b author?

**Comment by tarmot** [comment]
Many blogs have only one user account, yes. But since we're building network capabilities, we should also consider a wider deployment.

We can delay this change, but currently I have no idea how to display author information reliably when in aggregate views. We can't even rely on there being user id 0 in an installation, so in effect only the custom attribution option is possible to implement.

When thinking about this, I also saw that it may be useful to separate limiting the choice of license and attribution. In some settings, the organization may want to dictate CC BY-SA for all content, but want individual attribution.

In my proposal (title) and (author) are text fields, which can be filled out by the admin.

So the difference between 4.a and 4.b is that in 4.a all posts are attributed to one entity (person or organization), whose name is written into the text field in wp-admin. In 4.b each post is attributed to its actual author, using that author's display name.

**Comment by BjornW** [comment]
I think we may have had a small miscommunication: the plugin will work with one or hundreds of authors, regardless of using it in a single WordPress or Network WordPress installation :)  

I'm pretty sure the current approach will allow us "to display author information reliably when in aggregate views" and allow other attribution options than the custom attribution. I like your idea of separating the attribution from the license and I also think the current approach should/will enable this. 

Could you can write user stories describing how a particular type of user (persona) would like to license their content. We can use these to test if the plugin allows this. If it doesn't we can use it to fix the plugin. This makes it easier for me to understand what your objective is with regards to certain changes. 

For example: 
"The University of Amsterdam has a student website. The University has a policy stating all student created content should be licensed CC-BY-SA and attributed to the respective student."

**Comment by tarmot** [comment]
I wrote a few stories. And there's a few creeping features in there...
https://github.com/tarmot/wp-cc-plugin/wiki/User-stories

We probably need to add options for CC0 and for "All rights reserved" into the selection of licenses.

**Comment by BjornW** [comment]
Great! CC0 is already included with the new 4.0 license chooser :) 
![screenshot from 2013-12-02 16 10 06](https://f.cloud.github.com/assets/65042/1655502/def1af0e-5b63-11e3-8743-ac2c14d0eae4.png) One of the reasons an API is nice to have instead of a static solution ;)

**Comment by BjornW** [comment]
A screenshot of multiple licenses selected in a aggregated view.
![screenshot from 2013-12-02 16 39 11](https://f.cloud.github.com/assets/65042/1655755/fb818294-5b67-11e3-80f6-f539a96cce97.png).

**Comment by BjornW** [comment]
Thinking out loud: How to deal with the widget?
- If the widget is shown on a page with multiple items it will _ALWAYS_ display the default site/network license including the warning text stating items may have a different license than the chosen site license. The items (posts) will display their own individual license using (the_content/the_excerpt) filters
  If the attribution is set to display_name on a page with multiple items on it the author name it will _NOT_ show the author name, but instead display the text 'attribute the respective author(s). Because we don't know which author to show...individual posts on the multiple items page should display the author name otherwise one cannot attribute correctly.

or we check if the author name is the same for all items and just display the author name? 

NB: This does not solve the issue with embedded items such as YouTube movies nor does it for attached media like images etc.

**Comment by tarmot** [comment]
When there are multiple posts with various authors, we can simply not show attribution information in the widget. The individual filter-produced license information will have author information.

**Comment by BjornW** [comment]
Your last comment has been addressed in #22 I will close this thread for now
