### ISSUE TITLE
Add version to the plugin for easier updates

### ISSUE THREAD

**Issue by BjornW** [tarmot/wp-cc-plugin#13]

**Comment by tarmot** [comment]
Also fix the author information in readme and other plugin metadata.

**Comment by tarmot** [comment]
The original WpLicense ended in version 1.2.2. So when we replace it, we need to bump the version number to a higher value.

**Comment by BjornW** [comment]
I've done this in this commit https://github.com/tarmot/wp-cc-plugin/commit/5a89483c5304558ae5172013456b882adf5a131b, but I still need to also add the version nr in the database so we can use for migration of old settings

**Comment by BjornW** [comment]
Used the version number 2.0 to distinct us from the previous WPLicense plugin in the readme and files. Need to add this version number to the database as well, opened a new ticker for that. See #21 so closing this one.
