### ISSUE TITLE
Fix print_license_html()

### ISSUE THREAD

**Issue by BjornW** [tarmot/wp-cc-plugin#14]
This function is crucial for displaying the license. Check and make sure all data is included. See also https://github.com/tarmot/wp-cc-plugin/issues/10#issuecomment-26786745 and the output of the current license chooser at creativecommons.org

**Comment by tarmot** [comment]
I checked, and the html display matches that of the 4.0 license chooser's output.

**Comment by tarmot** [comment]
Additionally, the strings used in the widget display should match _exactly_ those used in the Transifex translations, so they can be reused automatically.

**Comment by BjornW** [comment]
I will close this issue since the html output is technically correct and translations are being done using GNU Gettext for now. In the future we may create a tool to convert Transifex to PO / MO files.
