### ISSUE TITLE
Ensure migration from original WpLicense

### ISSUE THREAD

**Issue by tarmot** [tarmot/wp-cc-plugin#18]
The original WpLicense had the option 'cc_content_license', which contains the license name (as returned by the json call, as well as 'cc_content_license_uri' and 'cc_content_license_img'.

Our code should detect if these old values exist and migrate smoothly.

Another alternative (if the contents are compatible) is to use the same options as the original plugin.

**Comment by BjornW** [comment]
I'd like to first get our first release out the door and wait for user feedback. So for now I've closed this item and labeled it 'maybe-in-the-future'
