### ISSUE TITLE
Add option to set license per blog or even per multisite network

### ISSUE THREAD

**Issue by BjornW** [tarmot/wp-cc-plugin#2]
We need to decide what the hierarchy of the choices is, e.g. does the blog-wide setting overrule the user's chosen license or is it the other way?

**Comment by BjornW** [comment]
@tarmot: do you already have an idea for the hierarchy of the overriding of the license? I'm thinking of: 

|- WordPress Multisite Network --> sets default for all blogs in it's network 
|---- A WordPress blog/site --> Gets default from Network or in Single install sets the default for it's site
|-------- Author --> Gets default from site and can be overridden by user
|------------ Post/Page/CPT --> Gets default from Author can be changed by user (not-necessarily it's author)

Is this along the same lines you were thinking?

**Comment by tarmot** [comment]
Yes. Although I had not though about specifying post type specific defaults. I'm not sure if it's needed. Might be useful, might just complicate the UI.

And the last level would be object-specific custom license, so the default (coming from the tree you described) is used to create the initial license for a new object, and this can be changed by the author (or anyone with edit rights to the object).

**Comment by BjornW** [comment]
The object specific license would be using the default of it's parent until changed. In other words the override is only valid for that particular instance. As for the per post-type: that's not what I implied, it would be a option on the post/page interface to set the license for that particular post or page.

**Comment by tarmot** [comment]
OK, so we're in agreement. I think the code base from License with my fixes should more or less implement this behaviour already.

**Comment by BjornW** [comment]
@tarmot: as you might notice I have not used your modifications as-is, because I find it quite hard to refactor the original license plugin code therefor some parts are more or less rewritten. This makes your modifications obsolete, although I still use them to guide myself in the right direction :) Have a look at this huge commit: https://github.com/tarmot/wp-cc-plugin/commit/9a17892f5cc6c7e586033390bbe0dbbb0c277e7d and you will see what I mean. The first steps towards licensing per network, site, user or content are in place. Needs more work & testing though!

**Comment by tarmot** [comment]
OK, looks good. I don't mind becoming obsolete. :)

**Comment by BjornW** [comment]
A license can be set for the whole network or if the network owner allows it per site. The per site option will only work if: 
1. In Network -> Settings -> Network Settings the option 'Allow siteadmins to change their site's license' is checked (by default)

**Comment by tarmot** [comment]
Works correctly.
