### ISSUE TITLE
Does not currently use CC 4.0

### ISSUE THREAD

**Issue by mzeinstra** [tarmot/wp-cc-plugin#20]
While I can select 4.0 as a license, it does not present 4.0 on the front-end, but the 3.0 variant.

**Comment by BjornW** [comment]
It should automagically use the 4.0 version, which branch of the plugin have you used?

**Comment by mzeinstra** [comment]
I believe I downloaded Tarmo Mods
-- 
Kennisland  | www.kennisland.nl | t +31205756720 | m +31643053919 | @mzeinstra

On 18 Feb 2014 at 15:56:16 , BjornW (notifications@github.com) wrote:

It should automagically use the 4.0 version, which branch of the plugin have you used?

**Comment by BjornW** [comment]
That's a very old branch, use the feature-content-filter branch for now. After we release an alpha version I'll clean up older branches to prevent any confusion.

**Comment by mzeinstra** [comment]
Wait I was wrong, I did use the feature-content-filter branch.

**Comment by BjornW** [comment]
Weird, in that branch you should see the 4.0 version applied.

**Comment by mzeinstra** [comment]
I’ve attached a screenshot where you see the footer implementation. You can also see the URL that is used, which points to 3.0
![screen shot 2014-02-18 at 16 21 32](https://f.cloud.github.com/assets/5627431/2196522/a1fc61b8-98b0-11e3-96f7-d2ce78228c4e.png)

**Comment by BjornW** [comment]
Really strange, which language of WordPress are you using?

**Comment by tarmot** [comment]
When I installed the plugin, it by default used a 3.0 version license. But if I go to general settings and choose a license, it will switch to a 4.0 license.

**Comment by BjornW** [comment]
I have changed the default version of the license to 4.0 in the develop branch, see https://github.com/tarmot/wp-cc-plugin/commit/b14e566df9b8539625145d7123f9f2d0511947ff 

@mzeinstra if you select a license in your current version of the plugin does it select the 4.0 version?

**Comment by BjornW** [comment]
I'll close this issue for now, feel free to re-open it if this issue is popping up again.
