### ISSUE TITLE
Incorrect license shown on multiple post views

### ISSUE THREAD

**Issue by tarmot** [tarmot/wp-cc-plugin#22]
When showing a page with multiple posts (archive page, for example), each excerpt is prefixed by the blog general license and a warning. This is incorrect. Either the post-specific prefixed license should be that of the individual post (and no warning), or the license should not be displayed there at all. It will be shown in the footer or a widget anyways.

**Comment by BjornW** [comment]
I've removed the license per post. The widget should automatically show the site / network license on multiple items pages such as archives and categories including the warning. On single post/page pages it will display the item's license without a warning.
