### ISSUE TITLE
Text color should be theme-aware if possible

### ISSUE THREAD

**Issue by tieguy** [tarmot/wp-cc-plugin#25]
I'm not sure if WP supports having plugins know about theme colors, but the plugin doesn't- I end up with dark text on the dark background of my footer. 

You can see it at http://lu.is/ if you want to see what I mean (the white license text is hand-coded HTML; the darker text is the one provided by the plugin).

**Comment by BjornW** [comment]
@tieguy Thanks for reporting this issue. 
We print out the license text as plain HTML without any styling associated with it, so it should use your WordPress' theme's CSS. This should make it easy to integrate the plugin with your site.  In your case it seems this is an issue with your theme's styling and not an issue with the plugin so I'll close this issue.
