### ISSUE TITLE
"Attribution work to name:" is a weird string, doesn't match the displayed text

### ISSUE THREAD

**Issue by tieguy** [tarmot/wp-cc-plugin#26]
The settings ask you to provide "Attribution work to name:" and then the displayed text says "This work by ____ is licensed...". Seems like the setting should be "Author to attribute"?

**Comment by BjornW** [comment]
@tieguy I'm not sure what you mean? Could you please explain this further?

**Comment by tieguy** [comment]
The text describing the field in the settings makes it sound like the field is for the name of the _work_ - for example, "Luis Villa's blog". The way the field is _used_ in the footer makes it clear that the field should have the _name of the author_.

**Comment by tarmot** [comment]
It's probably best to use the strings used in pane 3 of http://creativecommons.org/choose/
That way they are also translated to a number of languages.

**Comment by tieguy** [comment]
Huh, that is the same string already used. And that's an awful string,
especially out of context.

Alternatively, it might be better by default to attribute (at least by
default) to the post's author + link to the post's author page?

**Comment by BjornW** [comment]
@tieguy @tarmot I have trouble finding this string. Where did you find this, please paste the url. Are you using wplicense? Which version?

**Comment by tarmot** [comment]
Well, if it's the same string as in the license chooser, then the original bug report had it misspelled. I say we keep the same string as the chooser, at least for now.
