### ISSUE TITLE
Porting preference doesn't seem to stick?

### ISSUE THREAD

**Issue by tieguy** [tarmot/wp-cc-plugin#28]
I've now selected "unported" twice, and hit save twice, and I seem to end up with United States each time despite that.

**Comment by BjornW** [comment]
@tieguy Could you provide the exact steps you've performed so I can try to reproduce this issue?

**Comment by BjornW** [comment]
@tieguy after digging a bit further into your issues I'm beginning to suspect you're using a different plugin. Could you please provide a screenshot of the plugin details?

**Comment by BjornW** [comment]
I'll close this issue for now, because I cannot reproduce the issue & I suspect @tieguy may be using a different plugin.
