### ISSUE TITLE
Allow localization of both plugin interface as well as selection of license

### ISSUE THREAD

**Issue by BjornW** [tarmot/wp-cc-plugin#4]

**Comment by BjornW** [comment]
Using the Chooser with the partner url I can change the selection of a license using the wplang option automatically. For the static option (future) a different approach is needed. See also #12

**Comment by tarmot** [comment]
The strings needed in the display code are in Transifex, but the syntax is not directly compatible with php's i18n.

For example:

```
%(work_title)s by %(work_author)s is licensed under a <a rel="license" href="%(license_url)s">Creative Commons %(license_name)s License</a>.
```

that we can collect from Transifex in dozens of languages (and the order of the actual placeholders can vary) should be converted to something like

```
%1$s by %2$s is licensed under a <a rel="license" href="%3$s">Creative Commons %4$s License</a>.
```

so unless there's a ready-made function that does this, a series of substring match&replaces need to happen.

**Comment by BjornW** [comment]
For now I have used the default WordPress method of GNU Gettext's PO and MO files. The amount of strings is very limited: it took me between 10 and 15 minutes to translate all strings into Dutch. For now I propose to use this and look further into using a standalone tool to match strings between PO files and Transifex.
