### ISSUE TITLE
Allow override license per author

### ISSUE THREAD

**Issue by tarmot** [tarmot/wp-cc-plugin#7]

**Comment by BjornW** [comment]
This should work now. Keep in mind the widget display code is still rough and lacks for instance the correct attribution, but you should be able to change a user's license and make it differ from the site or network license. Note, this is only possible if: 
1. In Network -> Settings -> Network Settings the option 'Allow siteadmins to change their site's license' is checked (by default)
2. In the Site -> Settings -> General the option 'Allow users override site license' is checked (by default)

**Comment by tarmot** [comment]
Works as it should. Overridden licenses will not be shown if the override option is disabled.
