### ISSUE TITLE
Current license chooser future-proof?

### ISSUE THREAD

**Issue by BjornW** [tarmot/wp-cc-plugin#9]
I was looking into locales for the plugin and more specifically to use it as a default from the plugin to the CC license chooser. In other words we can easily grab the current WP locale and use this as a default for the CC license chooser. After looking into the current approach which uses an url apparently specifically for partners(?) and which has a distinct different look/interaction and I presume includes less metadata than the current license chooser on CC.org I was getting a bit worried if this url based approach is still the best method to choose a license. There's also a REST API, but the docs at least have not been updated since beginning of 2011. If we need to switch over to the REST API (which uses XML to communicate) we probably should be doing this sooner than later. 

Btw I've just sent a mail to cc-devel on this as well. @tarmot: I've cc-ed you as well.

**Comment by BjornW** [comment]
A bit more background info: 
Current approach: http://wiki.creativecommons.org/Partner_Interface
Possible other option:http://wiki.creativecommons.org/Creative_Commons_Web_Services

**Comment by tarmot** [comment]
When the license chooser switches to 4.0 licenses, at least the jurisdiction choice goes away, simplifying things. This means that jurisdiction is no longer needed (if it were, I'd use it as a separate option for the plugin), just the visible text localizations to an appropriate language.
Hopefully as the change to 4.0 is made, things won't break but remain backward-compatible.
I would not be too worried about the docs not being updated... The code (at least the API) has been pretty stable. But best to wait for more knowing replies from the cc-devel list.

**Comment by BjornW** [comment]
So far no response from the cc-devel list. For now I will keep the original approach and enhance this

**Comment by BjornW** [comment]
The CC license have changed to version 4.0 and so has the partner url. The plugin uses this and gets the 4.0 version of the license including CC0, therefor this issue can be closed.
